baseURL = 'https://balibaru.github.io/hugo/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "m10c"

[params]
  author = "Christopher Hart"
  description = "A blog about all things technical."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/ChristopherJHart"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/_ChrisJHart"